### ISSUE TITLE
Ability to generate reports

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#102]
https://github.com/tma1/dossier

Be able to quickly write configs to generate arbitrary reports.

Some example reports that would be useful:
- #78
- Carnival Closeout Reports (with charges, fines, tool notes, etc.)

**Comment by purelogiq** [comment]
I was just looking through #78 so that I can create some initial reports for this feature. I know about booth chairs and scc members, but, I was wondering what "Builders" are? Are they just all participants (or all other participants besides BC and SCC)?

Also would #78 be 1 report with 3 columns or 3 reports each with 1 column.

Lastly would you guys like to see any other initial reports? Perhaps some that make use of parameters?

**Comment by arakla** [comment]
Builders are members of all booth building orgs. Although there may be
other "orgs" that should be included in this list.

**Comment by pkoenig10** [comment]
@purelogiq Builders are all members of building organizations (having type Fraternity, Sorority, Independent, Blitz, or Concessions).  It would be nice to have the option to to choose the organization or output all builders.  It should be 3 reports each with one column because the information would be used in different contexts.

Two additional reports come to mind:

1. Charges.  Specifically being able to get all charges for a specific org and being able to choose store purchases, fines, or both.  It would be super helpful to create a sort of meta-report that can run the report once for each org and create multiple outputs.

2. Tools.  Being able to output all tools, with the option to filter by tool type (and less importantly checkout status).  This would be mostly useful for generating a hard copy of our tool inventory.

Other than that I can't think of any other places where reports would be useful.  But hopefully with this framework, adding new ones in the future will be easy. :)

**Comment by purelogiq** [comment]
Got it, thanks for the clarifications.
