### ISSUE TITLE
Tool types break organization tool pages

### ISSUE THREAD

**Issue by pkoenig10** [sc0v/binder-app#170]
For example (/organizations/1/tools).  This should show only tools checked out to an organization and should not have the check in/out filter.  This may be a little tricky to get working.

**Comment by purelogiq** [comment]
I can't find any way to get to that page other than clicking "hardhats" on the org page. Since the org page already has a tools tab, do you want that page to only show hardhats or everything checked out by the org. Also if the filters worked (i.e. limited to what the org had) would you like to keep them?

**Comment by pkoenig10** [comment]
@purelogiq here's what I'm thinking.  We remove the Members and "Hardhats" buttons.  At the bottom of the organization tools partial, there is "View more..." link.  Lets change this to "View all..." and show it anytime the organization has at least 1 tool checked out.  This will then take them to a tool view (limited to what the org has) where all the filters work.

**Comment by purelogiq** [comment]
Will be fixed tonight, sorry for the delay
