### ISSUE TITLE
Access Issues

### ISSUE THREAD

**Issue by csweintraub** [sc0v/binder-app#77]
SCC should be able to view all phone numbers, tool checkouts and waiver stauses for all orgs.

Booth Chairs should be able to view the cell phone numbers, tool checkouts and waiver statuses for their org only.

General members should be able to view cell phones for their org only.

**Comment by minigeek** [comment]
The SCC stuff is working. 

Booth chairs can currently see all numbers (made more sense when only chairs had numbers, so that they could get in contact with chairs from other orgs) are we sure we want to remove this access for them? Or can we just allow them to see numbers of people who are chairs in some org?

Members can currently only see their own phone number (they should have the number of the people in their org) is that ok?.

**Comment by csweintraub** [comment]
No, keep the access as we have it now. Rigth now everything is good.
